// <auto-generated />
using System;
using Dashboard.HDNManagementAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dashboard.HDNManagementAPI.Migrations
{
    [DbContext(typeof(HDNManagementDbContext))]
    [Migration("20200313120342_InitialHDNManagementDb")]
    partial class InitialHDNManagementDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard.HDNManagementAPI.Model.HDN", b =>
                {
                    b.Property<int>("HdnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BerichtLocatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BerichtNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HdnOptionId")
                        .HasColumnType("int");

                    b.Property<int?>("OmgevingId")
                        .HasColumnType("int");

                    b.HasKey("HdnId");

                    b.HasIndex("HdnOptionId");

                    b.HasIndex("OmgevingId");

                    b.ToTable("Hdn");
                });

            modelBuilder.Entity("Dashboard.HDNManagementAPI.Model.HdnOption", b =>
                {
                    b.Property<int>("HdnOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverbruggingBedrag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TussenPersoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfHypotheek")
                        .HasColumnType("int");

                    b.Property<bool>("UseGivenFirstClient")
                        .HasColumnType("bit");

                    b.Property<bool>("UseGivenSecondClient")
                        .HasColumnType("bit");

                    b.Property<bool>("UseGivenTussenPersoon")
                        .HasColumnType("bit");

                    b.Property<bool>("UseNHG")
                        .HasColumnType("bit");

                    b.Property<bool>("UseOverbruggingBedrag")
                        .HasColumnType("bit");

                    b.HasKey("HdnOptionId");

                    b.ToTable("HdnOption");
                });

            modelBuilder.Entity("Dashboard.HDNManagementAPI.Model.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OmgevingId")
                        .HasColumnType("int");

                    b.HasKey("LabelId");

                    b.HasIndex("OmgevingId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("Dashboard.HDNManagementAPI.Model.Omgeving", b =>
                {
                    b.Property<int>("OmgevingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OmgevingNaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OmgevingId");

                    b.ToTable("Omgeving");
                });

            modelBuilder.Entity("Dashboard.HDNManagementAPI.Model.HDN", b =>
                {
                    b.HasOne("Dashboard.HDNManagementAPI.Model.HdnOption", "HdnOption")
                        .WithMany()
                        .HasForeignKey("HdnOptionId");

                    b.HasOne("Dashboard.HDNManagementAPI.Model.Omgeving", "Omgeving")
                        .WithMany()
                        .HasForeignKey("OmgevingId");
                });

            modelBuilder.Entity("Dashboard.HDNManagementAPI.Model.Label", b =>
                {
                    b.HasOne("Dashboard.HDNManagementAPI.Model.Omgeving", null)
                        .WithMany("Labels")
                        .HasForeignKey("OmgevingId");
                });
#pragma warning restore 612, 618
        }
    }
}
